export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESSFUL = 'ADD_USER_SUCCESSFUL';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESSFUL = 'GET_USERS_SUCCESSFUL';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESSFUL = 'DELETE_USER_SUCCESSFUL';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const GET_UPDATE_USER = 'GET_UPDATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESSFUL = 'UPDATE_USER_SUCCESSFUL';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
